"""
Central configuration.

The runtime intentionally keeps secrets and Associates-generated URLs in the environment.
Public campaign facts can be stored in YAML, but control tokens, model API keys, and
Amazon Special Links must never be committed.
"""

from __future__ import annotations

import os
from dataclasses import dataclass
from pathlib import Path
from urllib.parse import parse_qs, urlparse
from zoneinfo import ZoneInfo, ZoneInfoNotFoundError

DEFAULT_PAYPRO_PRODUCT_URL = (
    "https://www.paypro.nl/producten/WegMetDieKilos_Bronze_Plan/114766/183297"
)
DEFAULT_AMAZON_PRODUCT_URL = "https://www.amazon.com/dp/B0BZYCJK89"


def _bool(name: str, default: bool) -> bool:
    value = os.getenv(name)
    if value is None:
        return default
    return value.strip().lower() in {"1", "true", "yes", "on"}


def _int(name: str, default: int, minimum: int = 0) -> int:
    raw = os.getenv(name)
    if raw is None:
        return default
    try:
        return max(minimum, int(raw))
    except ValueError:
        return default


def _float(name: str, default: float, minimum: float = 0.0) -> float:
    raw = os.getenv(name)
    if raw is None:
        return default
    try:
        return max(minimum, float(raw))
    except ValueError:
        return default


def _csv(name: str, default: str) -> tuple[str, ...]:
    raw = os.getenv(name, default)
    return tuple(value.strip() for value in raw.split(",") if value.strip())


def is_amazon_special_link(value: str) -> bool:
    """Return True only for a normal Amazon tagged URL or a SiteStripe short URL.

    The application never creates, appends to, or otherwise rewrites Amazon links.
    An owner must paste the exact link created in Associates SiteStripe or Associates
    Central. Amazon uses both tagged amazon-domain URLs and ``amzn.to`` short links.
    """
    parsed = urlparse(value)
    host = parsed.netloc.lower().split(":", maxsplit=1)[0]
    if parsed.scheme != "https":
        return False
    if host == "amzn.to":
        return bool(parsed.path.strip("/"))
    if not (host == "amazon.com" or host.endswith(".amazon.com")):
        return False
    return bool(parse_qs(parsed.query).get("tag"))


@dataclass(frozen=True, slots=True)
class Settings:
    app_name: str
    app_env: str
    data_dir: Path
    database_path: Path
    campaign_config_path: Path
    public_base_url: str
    affiliate_provider: str
    amazon_product_url: str
    amazon_associate_url: str
    paypro_product_url: str
    paypro_affiliate_id: str
    paypro_affiliate_url_template: str
    affiliate_disclosure: str
    control_token: str
    webhook_token: str
    paypro_webhook_secret: str
    cors_origins: tuple[str, ...]
    llm_provider: str
    llm_model: str
    llm_fallback_model: str
    llm_max_output_tokens: int
    llm_timeout_seconds: float
    llm_max_requests_per_run: int
    llm_max_requests_per_hour: int
    llm_max_requests_per_day: int
    heartbeat_enabled: bool
    heartbeat_interval_seconds: float
    auto_run_due_campaigns: bool
    schedule_timezone: str
    draft_only: bool
    website_enabled: bool
    log_level: str

    @property
    def production(self) -> bool:
        return self.app_env.lower() in {"production", "prod"}

    @property
    def llm_available(self) -> bool:
        if self.llm_provider == "deterministic":
            return False
        return bool(os.getenv("OPENAI_API_KEY"))

    @property
    def default_product_url(self) -> str:
        if self.affiliate_provider == "amazon":
            return self.amazon_product_url
        return self.paypro_product_url

    @property
    def direct_affiliate_links_only(self) -> bool:
        return self.affiliate_provider == "amazon"

    def validate(self) -> None:
        if self.affiliate_provider not in {"amazon", "paypro"}:
            raise ValueError("AFFILIATE_PROVIDER must be either 'amazon' or 'paypro'")
        for name, value in {
            "DEFAULT_PRODUCT_URL": self.default_product_url,
            "PUBLIC_BASE_URL": self.public_base_url,
        }.items():
            parsed = urlparse(value)
            if parsed.scheme not in {"http", "https"} or not parsed.netloc:
                raise ValueError(f"{name} must be an absolute HTTP(S) URL")
        if self.affiliate_provider == "amazon" and self.amazon_associate_url:
            if not is_amazon_special_link(self.amazon_associate_url):
                raise ValueError(
                    "AMAZON_ASSOCIATE_URL must be the exact tagged or amzn.to link generated by Amazon Associates"
                )
        if self.affiliate_provider == "paypro":
            allowed_placeholders = ("{product_url}", "{affiliate_id}")
            if not any(value in self.paypro_affiliate_url_template for value in allowed_placeholders):
                raise ValueError(
                    "PAYPRO_AFFILIATE_URL_TEMPLATE must contain {product_url} or {affiliate_id}"
                )
        if self.production and not self.control_token:
            raise ValueError("CONTROL_TOKEN is required in production")
        if self.production and not self.webhook_token:
            raise ValueError("WEBHOOK_TOKEN is required in production")
        if self.production and self.public_base_url.startswith("http://"):
            raise ValueError("PUBLIC_BASE_URL must use HTTPS in production")
        try:
            ZoneInfo(self.schedule_timezone)
        except ZoneInfoNotFoundError as exc:
            raise ValueError("SCHEDULE_TIMEZONE must be a valid IANA timezone") from exc


def load_settings() -> Settings:
    data_dir = Path(os.getenv("DATA_DIR", "./data")).expanduser().resolve()
    database_default = data_dir / "campaign_automaton.db"
    settings = Settings(
        app_name=os.getenv("APP_NAME", "Amazon Associate Campaign Automaton"),
        app_env=os.getenv("APP_ENV", "development"),
        data_dir=data_dir,
        database_path=Path(os.getenv("DATABASE_PATH", str(database_default)))
        .expanduser()
        .resolve(),
        campaign_config_path=Path(
            os.getenv("CAMPAIGN_CONFIG_PATH", "config/campaign.yaml")
        )
        .expanduser()
        .resolve(),
        public_base_url=os.getenv("PUBLIC_BASE_URL", "http://localhost:8000").rstrip("/"),
        affiliate_provider=os.getenv("AFFILIATE_PROVIDER", "amazon").strip().lower(),
        amazon_product_url=os.getenv("AMAZON_PRODUCT_URL", DEFAULT_AMAZON_PRODUCT_URL).strip(),
        amazon_associate_url=os.getenv("AMAZON_ASSOCIATE_URL", "").strip(),
        paypro_product_url=os.getenv("PAYPRO_PRODUCT_URL", DEFAULT_PAYPRO_PRODUCT_URL).strip(),
        paypro_affiliate_id=os.getenv("PAYPRO_AFFILIATE_ID", "").strip(),
        paypro_affiliate_url_template=os.getenv(
            "PAYPRO_AFFILIATE_URL_TEMPLATE", "{product_url}"
        ),
        affiliate_disclosure=os.getenv(
            "AFFILIATE_DISCLOSURE",
            "Disclosure: As an Amazon Associate I earn from qualifying purchases. (paid link)",
        ),
        control_token=os.getenv("CONTROL_TOKEN", ""),
        webhook_token=os.getenv("WEBHOOK_TOKEN", ""),
        paypro_webhook_secret=os.getenv("PAYPRO_WEBHOOK_SECRET", "").strip(),
        cors_origins=_csv("CORS_ORIGINS", "http://localhost:3000,http://localhost:8000"),
        llm_provider=os.getenv("LLM_PROVIDER", "auto").strip().lower(),
        llm_model=os.getenv("LLM_MODEL", "gpt-5-mini").strip(),
        llm_fallback_model=os.getenv("LLM_FALLBACK_MODEL", "gpt-5-nano").strip(),
        llm_max_output_tokens=_int("LLM_MAX_OUTPUT_TOKENS", 3500, 256),
        llm_timeout_seconds=_float("LLM_TIMEOUT_SECONDS", 90.0, 5.0),
        llm_max_requests_per_run=_int("LLM_MAX_REQUESTS_PER_RUN", 6, 1),
        llm_max_requests_per_hour=_int("LLM_MAX_REQUESTS_PER_HOUR", 30, 1),
        llm_max_requests_per_day=_int("LLM_MAX_REQUESTS_PER_DAY", 150, 1),
        heartbeat_enabled=_bool("HEARTBEAT_ENABLED", True),
        heartbeat_interval_seconds=_float("HEARTBEAT_INTERVAL_SECONDS", 30.0, 1.0),
        auto_run_due_campaigns=_bool("AUTO_RUN_DUE_CAMPAIGNS", False),
        schedule_timezone=os.getenv("SCHEDULE_TIMEZONE", "Europe/Amsterdam").strip(),
        draft_only=_bool("DRAFT_ONLY", True),
        website_enabled=_bool("WEBSITE_ENABLED", False),
        log_level=os.getenv("LOG_LEVEL", "INFO").upper(),
    )
    settings.data_dir.mkdir(parents=True, exist_ok=True)
    settings.database_path.parent.mkdir(parents=True, exist_ok=True)
    settings.validate()
    return settings
