"""HTML dashboard for the protected AutoTrader paper/live-readiness API."""

from __future__ import annotations


DASHBOARD_HTML = r'''<!doctype html>
<html lang="nl">
<head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>AutoTrader | Portfolio Control Room</title>
<style>
:root{--bg:#07111f;--panel:#101e31;--panel2:#14263d;--line:#243954;--text:#e8f0fa;--muted:#8ea4bd;--green:#35d49a;--amber:#f5bd4f;--red:#ff6b7a;--blue:#61a7ff}
*{box-sizing:border-box}body{margin:0;background:radial-gradient(circle at 85% 0,#17345d 0,#07111f 42%);font-family:Inter,Segoe UI,Arial,sans-serif;color:var(--text);min-height:100vh}
.wrap{max-width:1380px;margin:auto;padding:28px}.top{display:flex;justify-content:space-between;align-items:center;gap:18px;margin-bottom:26px}.brand{display:flex;gap:14px;align-items:center}.logo{width:46px;height:46px;border-radius:14px;background:linear-gradient(135deg,#35d49a,#4386ff);display:grid;place-items:center;font-weight:900;color:#06101c}.eyebrow{color:var(--green);font-size:12px;text-transform:uppercase;letter-spacing:.14em;font-weight:800}.title{font-size:30px;font-weight:800;margin:3px 0}.sub{color:var(--muted);font-size:13px}.pill{border:1px solid var(--line);border-radius:999px;padding:9px 13px;color:var(--muted);font-size:12px}.pill b{color:var(--green)}
.login{max-width:430px;margin:10vh auto;background:rgba(16,30,49,.92);border:1px solid var(--line);border-radius:22px;padding:28px;box-shadow:0 24px 80px #0008}.login h1{margin-top:0}.field{display:grid;gap:7px;margin:14px 0}.field label{font-size:12px;color:var(--muted)}input{width:100%;background:#091728;border:1px solid var(--line);border-radius:10px;padding:12px;color:var(--text);outline:none}input:focus{border-color:var(--blue)}button{border:0;border-radius:10px;padding:11px 15px;font-weight:800;cursor:pointer;background:var(--green);color:#04131b}button.secondary{background:var(--panel2);color:var(--text);border:1px solid var(--line)}.err{color:var(--red);font-size:13px;min-height:20px;margin-top:10px}
.hidden{display:none!important}.grid{display:grid;grid-template-columns:repeat(4,1fr);gap:14px}.card{background:linear-gradient(145deg,rgba(20,38,61,.96),rgba(13,27,45,.96));border:1px solid var(--line);border-radius:17px;padding:19px;box-shadow:0 12px 35px #0002}.label{color:var(--muted);font-size:12px}.value{font-size:27px;font-weight:800;margin-top:8px}.green{color:var(--green)}.red{color:var(--red)}.amber{color:var(--amber)}.blue{color:var(--blue)}.section{margin-top:20px}.section h2{font-size:16px;margin:0 0 11px}.two{display:grid;grid-template-columns:1.25fr .75fr;gap:14px}.table{width:100%;border-collapse:collapse;font-size:13px}.table th{text-align:left;color:var(--muted);font-weight:600;padding:10px 8px;border-bottom:1px solid var(--line)}.table td{padding:12px 8px;border-bottom:1px solid #1c3049}.status{display:inline-flex;align-items:center;gap:7px}.dot{width:8px;height:8px;border-radius:99px;background:var(--green);box-shadow:0 0 12px var(--green)}.dot.off{background:var(--red);box-shadow:0 0 12px var(--red)}.metric{display:flex;justify-content:space-between;border-bottom:1px solid #1c3049;padding:12px 0;color:var(--muted)}.metric b{color:var(--text)}.bar{height:9px;border-radius:99px;background:#091728;overflow:hidden;margin-top:8px}.bar i{display:block;height:100%;background:linear-gradient(90deg,var(--green),var(--blue));border-radius:inherit}.notice{border-left:3px solid var(--amber);background:#2c2514;padding:12px 14px;color:#ead9ad;font-size:13px;border-radius:8px}.foot{color:var(--muted);font-size:11px;margin-top:22px;display:flex;justify-content:space-between;gap:10px}
@media(max-width:900px){.grid{grid-template-columns:repeat(2,1fr)}.two{grid-template-columns:1fr}}@media(max-width:560px){.wrap{padding:16px}.grid{grid-template-columns:1fr}.top{align-items:flex-start;flex-direction:column}}
</style></head><body>
<div id="login" class="login"><div class="eyebrow">Private control room</div><h1>AutoTrader dashboard</h1><p class="sub">Meld aan om portfolio- en positiedata te bekijken. Er worden geen orders vanuit dit dashboard geplaatst.</p><div class="field"><label>Gebruikersnaam</label><input id="username" autocomplete="username" value="admin"></div><div class="field"><label>Wachtwoord</label><input id="password" type="password" autocomplete="current-password"></div><div class="field"><label>Of API-key</label><input id="apikey" type="password" autocomplete="off" placeholder="X-API-Key (optioneel)"></div><button onclick="login()">Dashboard openen</button><div id="loginerr" class="err"></div></div>
<div id="app" class="hidden"><div class="wrap"><header class="top"><div class="brand"><div class="logo">AT</div><div><div class="eyebrow">Portfolio control room</div><div class="title">AutoTrader</div><div class="sub">Bitvavo monitoring · live updates · beveiligde sessie</div></div></div><div><span class="pill">Mode: <b id="mode">paper</b></span> <button class="secondary" onclick="refresh()">Vernieuwen</button> <button class="secondary" onclick="logout()">Uitloggen</button></div></header>
<div id="notice" class="notice">Live orders zijn vanuit deze webinterface uitgeschakeld. Controleer altijd de execution-status en limieten.</div>
<section class="section"><div class="grid"><div class="card"><div class="label">Portfolio waarde EUR</div><div id="eur" class="value">—</div><div id="eurdelta" class="sub">—</div></div><div class="card"><div class="label">Portfolio waarde BTC</div><div id="btc" class="value blue">—</div><div id="btcrate" class="sub">—</div></div><div class="card"><div class="label">PnL</div><div id="pnl" class="value">—</div><div id="pnlpct" class="sub">—</div></div><div class="card"><div class="label">Drawdown</div><div id="dd" class="value amber">—</div><div class="sub">Vanaf lokale equity-piek</div></div></div></section>
<section class="section two"><div class="card"><h2>Open posities</h2><table class="table"><thead><tr><th>Symbool</th><th>Side</th><th>Notional</th><th>PnL</th></tr></thead><tbody id="positions"><tr><td colspan="4" class="sub">Laden…</td></tr></tbody></table></div><div class="card"><h2>Execution & risk</h2><div class="metric"><span>Status</span><b id="execmode">—</b></div><div class="metric"><span>Dagelijkse exposure</span><b id="exposure">—</b></div><div class="metric"><span>Dagverlies</span><b id="loss">—</b></div><div class="metric"><span>Max per order</span><b id="maxtrade">—</b></div><div class="metric"><span>Max dagexposure</span><b id="maxdaily">—</b></div><div class="metric"><span>Max dagverlies</span><b id="maxloss">—</b></div></div></section>
<section class="section two"><div class="card"><h2>Strategieën</h2><table class="table"><thead><tr><th>Naam</th><th>Status</th><th>PnL</th><th>Trades</th></tr></thead><tbody id="strategies"><tr><td colspan="4" class="sub">Laden…</td></tr></tbody></table></div><div class="card"><h2>Runtime</h2><div class="metric"><span>Feed/ticker</span><b id="ticker">—</b></div><div class="metric"><span>Laatste update</span><b id="updated">—</b></div><div class="metric"><span>WebSocket</span><b id="socket">verbinden…</b></div><div class="bar"><i id="healthbar" style="width:0%"></i></div><div class="sub" style="margin-top:8px">Gezondheidsindicator op basis van ticker en laatste fout.</div></div></section>
<section class="section two"><div class="card"><h2>Bitpanda Fusion</h2><div class="metric"><span>Credentials aanwezig</span><b id="fusioncred">—</b></div><div class="metric"><span>Read-only authenticatie</span><b id="fusionauth">—</b></div><div class="metric"><span>Balance endpoint</span><b id="fusionendpoint">—</b></div><div class="metric"><span>Fusion order mode</span><b id="fusionmode">—</b></div><div class="metric"><span>Laatste controle</span><b id="fusionchecked">—</b></div><div id="fusionnote" class="notice" style="margin-top:12px">Geen Fusion-status geladen.</div></div><div class="card"><h2>Safety gates</h2><div class="metric"><span>Global mode</span><b id="safetymode">—</b></div><div class="metric"><span>Live Fusion orders</span><b id="fusionlive">—</b></div><div class="metric"><span>Emergency stop</span><b id="emergencystop">—</b></div><div class="metric"><span>Withdrawal/Transfer</span><b class="green">Niet gebruikt</b></div><div class="sub" style="margin-top:12px">Deze kaart toont alleen statusmetadata. Het dashboard plaatst geen orders.</div></div></section>
<div class="foot"><span id="last">Nog niet bijgewerkt</span><span id="apierror" class="red"></span><span>Alle waarden zijn door de API aangeleverd.</span></div></div></div>
<script>
let token=sessionStorage.getItem('at_token')||'', apiKey='', socket;
const $=id=>document.getElementById(id); const esc=v=>String(v??'—').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])); const money=v=>v==null?'—':'€ '+Number(v).toFixed(2); const num=v=>v==null?'—':Number(v).toFixed(6);
function headers(){let h={'Accept':'application/json'};if(token)h.Authorization='Bearer '+token;if(apiKey)h['X-API-Key']=apiKey;return h}
async function get(path){let r=await fetch(path,{headers:headers()});if(r.status===401||r.status===503)throw Error('Sessie ongeldig of dashboard-auth ontbreekt');if(!r.ok)throw Error('API fout '+r.status);return r.json()}
async function login(){ $('loginerr').textContent=''; apiKey=$('apikey').value.trim(); if(apiKey){token='';}else{try{let r=await fetch('/api/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username:$('username').value,password:$('password').value})});let d=await r.json();if(!r.ok)throw Error(d.detail||'Login mislukt');token=d.access_token;sessionStorage.setItem('at_token',token)}catch(e){$('loginerr').textContent=e.message;return}} $('login').classList.add('hidden');$('app').classList.remove('hidden');refresh();connect()}
function logout(){sessionStorage.removeItem('at_token');apiKey='';token='';location.reload()}
function renderReport(d){let a=d.account||{},p=d.pnl||{},b=d.balance||{},r=d.rates||{};$('eur').textContent=money(b.eur);$('btc').textContent=num(b.btc)+' BTC';$('pnl').textContent=money(p.eur);$('pnl').className='value '+(p.eur>=0?'green':'red');$('pnlpct').textContent=Number(a.pnl_pct||0).toFixed(2)+'% rendement';$('dd').textContent=Number(a.drawdown_pct||0).toFixed(2)+'%';$('eurdelta').textContent=money(p.usd)+' in USD';$('btcrate').textContent=r.btc_usd?'BTC/USD '+Number(r.btc_usd).toFixed(0):'BTC-koers niet beschikbaar';$('mode').textContent=d.mode||'paper'}
function renderExec(d){let l=d.limits||{};$('execmode').textContent=(d.mode||'paper')+' · '+(d.live_execution_capability||'onbekend');$('exposure').textContent='€ '+(d.daily_exposure_eur||'0');$('loss').textContent='€ '+(d.daily_loss_eur||'0');$('maxtrade').textContent='€ '+(l.max_trade_eur||'—');$('maxdaily').textContent='€ '+(l.max_daily_exposure_eur||'—');$('maxloss').textContent='€ '+(l.max_daily_loss_eur||'—')}
function renderStrategies(d){let rows=d.pnl_per_strategy||[];$('strategies').innerHTML=rows.length?rows.map(x=>`<tr><td>${esc(x.name)}</td><td><span class="status"><i class="dot ${x.status==='running'?'':'off'}"></i>${esc(x.status)}</span></td><td>${money(x.pnlAllTime)}</td><td>${esc(x.tradesToday??0)}</td></tr>`).join(''):'<tr><td colspan="4" class="sub">Geen strategieën</td></tr>'}
function renderRisk(d){let pos=d.open_positions||d.positions||[];if(!Array.isArray(pos))pos=[];$('positions').innerHTML=pos.length?pos.map(x=>`<tr><td>${esc(x.symbol||x.market)}</td><td>${esc(x.side)}</td><td>${money(x.notional_eur??x.notional)}</td><td>${money(x.pnl_eur??x.pnl)}</td></tr>`).join(''):'<tr><td colspan="4" class="sub">Geen open posities</td></tr>'}
function renderFusion(d,e){let ok=d.authenticated===true;$('fusioncred').textContent=d.credentials_present?'aanwezig':'ontbreekt';$('fusioncred').className=d.credentials_present?'green':'red';$('fusionauth').textContent=ok?'geslaagd':(d.category||'mislukt');$('fusionauth').className=ok?'green':'red';$('fusionendpoint').textContent=d.endpoint||'balance probe';$('fusionmode').textContent=(e?.mode||'shadow')+' · live '+(e?.live_execution_capability||'uit');$('fusionchecked').textContent=new Date().toLocaleTimeString();$('fusionnote').textContent=ok?'Read-only balans-authenticatie geslaagd; bedragen worden niet in deze kaart getoond.':'Read-only balans-authenticatie niet geslaagd: '+(d.category||'onbekend');$('safetymode').textContent=e?.mode||'shadow';$('fusionlive').textContent=e?.live_execution_capability||'uit';$('emergencystop').textContent=e?.emergency_stop?'ACTIEF':'niet actief'}
function setSectionError(label,error){$('apierror').textContent=label+': '+(error?.message||'niet beschikbaar')}
async function refresh(){let now=new Date().toLocaleString();$('last').textContent='Bijwerken…';$('apierror').textContent='';let entries=await Promise.allSettled([get('/api/paper/report'),get('/api/execution/status'),get('/api/pnl/summary'),get('/api/health'),get('/api/security/bitpanda-fusion'),get('/api/risk/status')]);let [r,e,s,h,f,k]=entries;let fail=(entry,label)=>{if(entry.status==='rejected')setSectionError(label,entry.reason)};if(r.status==='fulfilled')renderReport(r.value);else fail(r,'Portfolio');if(e.status==='fulfilled')renderExec(e.value);else fail(e,'Execution');if(s.status==='fulfilled')renderStrategies(s.value);else fail(s,'PnL');if(h.status==='fulfilled'){$('ticker').textContent=h.value.runtime?.ticker_running?'actief':'gestopt';$('updated').textContent=new Date().toLocaleTimeString();$('healthbar').style.width=h.value.runtime?.last_tick_error?'25%':'100%'}else fail(h,'Runtime');if(f.status==='fulfilled')renderFusion(f.value,e.status==='fulfilled'?e.value:{});else fail(f,'Fusion');if(k.status==='fulfilled')renderRisk(k.value);else fail(k,'Risk');$('last').textContent='Bijgewerkt '+now}
function connect(){try{let scheme=location.protocol==='https:'?'wss':'ws';let q=apiKey?'?api_key='+encodeURIComponent(apiKey):token?'?access_token='+encodeURIComponent(token):'';socket=new WebSocket(`${scheme}://${location.host}/ws/paper${q}`);socket.onopen=()=>{$('socket').textContent='verbonden';$('socket').className='green'};socket.onmessage=e=>{try{renderReport(JSON.parse(e.data))}catch(_){}};socket.onclose=()=>{$('socket').textContent='herstellen…';setTimeout(connect,4000)}}catch(_){$('socket').textContent='niet beschikbaar'}}
if(token||apiKey){$('login').classList.add('hidden');$('app').classList.remove('hidden');refresh();connect()}
setInterval(()=>{if(!$('app').classList.contains('hidden'))refresh()},15000);
</script></body></html>'''


def dashboard_html() -> str:
    return DASHBOARD_HTML
